apiVersion: apps/v1
kind: Deployment
metadata:
  name: csark-healthcare-deploy
  labels:
    app: csark-healthcare-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csark-healthcare-deploy
  template:
    metadata:
      labels:
        app: csark-healthcare-deploy
    spec:
      containers:
      - name: csark-healthcare-container
        image: csark/healthcare-app
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: csark-banking-np-service
  labels:
    app: csark-banking-deploy
spec:
  selector:
    app: csark-banking-deploy

  type: NodePort
  ports:
  - nodePort: 31400
    port: 8081
    targetPort: 8081
